lesson 3.1
hawk911/thinknetica-go pull request #5
Opened 2020-11-07 12:17 UTC by hawk911

Lesson 3

2020-11-08 04:25 UTC, DmitriyVTitov requested changes
Переименовать и разделить функции.

2020-11-08 04:25 UTC, DmitriyVTitov commented on go-core/lesson_3/cmd/engine/main.go
> +var words string
глобальные переменные не приветствуются
уберите переменную в функцию, где она используется

2020-11-08 04:25 UTC, DmitriyVTitov commented on go-core/lesson_3/cmd/engine/main.go
> +}
верно

2020-11-08 04:25 UTC, DmitriyVTitov commented on go-core/lesson_3/cmd/engine/main.go
> +	p := crawler.Crawler{Url: url, Depth: depth}
crawler.Crawler - неудачное имя (масло маслянное)

2020-11-08 04:25 UTC, DmitriyVTitov commented on go-core/lesson_3/cmd/engine/main.go
> +func Searching(s Scanner) {
имя функции не должно быть герундием

2020-11-08 04:25 UTC, DmitriyVTitov commented on go-core/lesson_3/cmd/engine/main.go
> +}
Смысл использования интерфейса в данном случае в том, чтобы функцию, которая получает интерфейс как аргумент, можно было протестировать, передав в тесте заглушку.
У вас такая функция вот эта, но протестировать её невозможно, поскольку она делает всё на свете, включая ввод из консоли и вывод на экран.
Это всё необходимо разделить, используя метод рефакторинга "выделение функции", о котором я рассказывал на прошлой лекции (по тестированию).
Функция поиска должна возвращать найденные документы, а вводом и выводом должен занимать вызывающий код. В виде отдельных функций или прямо в `main()`.

2020-11-12 14:47 UTC, hawk911 commented on go-core/lesson_3/cmd/engine/main.go
> +}
Переделал.

2020-11-15 01:39 UTC, DmitriyVTitov approved these changes
Решено верно!

2020-11-15 01:39 UTC, DmitriyVTitov commented on go-core/lesson_3/cmd/engine/main.go
> +		fmt.Println("Enter some words that its need to find or leave empty for exit:")
Денис, пишите по-русски :)

2020-11-15 01:39 UTC, DmitriyVTitov commented on go-core/lesson_3/pkg/crawbot/crawbot.go
> +func NewScanner() *Scanner {
просто `New()`

2020-11-15 01:39 UTC, DmitriyVTitov commented on go-core/lesson_3/pkg/engine/engine.go
> +}
не стоит отдельной функции, вы сюда ничего не привнесли

2020-11-15 01:39 UTC, DmitriyVTitov commented on go-core/lesson_3/pkg/crawler/crawler.go
> +type Param struct {
что этот "парам" означает? совершенно неудачное имя.

2020-11-15 01:39 UTC, DmitriyVTitov commented on go-core/lesson_3/pkg/engine/engine_test.go
> +	}
верно!

2020-11-15 05:02 UTC, hawk911 commented on go-core/lesson_3/cmd/engine/main.go
> +		fmt.Println("Enter some words that its need to find or leave empty for exit:")
Я не в РФ работаю. Нас наоборот просят писать на английском :) У нас английский язык принят для общения в компании.

2020-11-15 05:05 UTC, hawk911 commented on go-core/lesson_3/pkg/engine/engine.go
> +}
Читабельность и два вызова, поэтому выделил в отдельную функцию

2020-11-15 05:15 UTC, merged